#!/usr/bin/env python
import os
import sys
from optparse import OptionParser

# load My Class
SHARE_DIR='/home/jhkim/work/share/python'
sys.path.append(SHARE_DIR)
from class_draw_unstruct import *


# need make read_variable_in_file in class_draw_unstruct

ngrids   = 1

varnames  = ['p']
nvars     = len(varnames)
filenames = ['' for i in range(ngrids)]
vars      = [[[] for j in range(nvars)] for i in range(ngrids)]
lats      = ['' for i in range(ngrids)]
lons      = ['' for i in range(ngrids)]
ncol      = [0 for i in range(ngrids)]
vars_d    = [[[] for j in range(ngrids)] for i in range(nvars)]

filenames[0] = '/data/jhkim/TestBed/KIM/Output/3.0.10/ne30/gnu/10h/SW_G/101/UP-20110725120000-000000.nc'

canvas = class_draw_unstruct(ngrids)
ncol[0] = canvas.read_variables_in_file_new(filenames[0],varnames,vars[0])
print len(vars), len(vars[0]), vars[0][0][0], vars[0][0][10]
lats[0], lons[0] = canvas.read_latlon_in_file(ncol[0],filenames[0],None,None)
for g in range(ngrids):
    for v in range(nvars):
        vars_d[v][g] = vars[g][v]
canvas.add_grid(lons[0],lats[0])
canvas.check_grid()
canvas.add_variable(varnames[0],vars_d[0])
canvas.draw(title='test',maptype=0,figname=None,ongrid=False,onbar=False,res=0)
canvas.show()


