#!/usr/bin/env python
#-------------------------------------------------------------------------------
# MODULE KiapsGrid
#
#> @brief
#>  - show status of batch jobs
#>
#> @date 13JAN2015
#>  - JH KIM(jh.kim@kiaps.org) : First written

import os
import sys
import time
import curses
import numpy as np
from optparse import OptionParser

opt = OptionParser()

# action: 'store', 'store_const', 'append', 'count', 'callback'
opt.add_option('-d', '--dir',     dest='dir',       default='./',  action='store',       help='Searching Drectory')
opt.add_option('-e', '--ext',     dest='ext',       default=[],    action='append',      help='Extension of Files')
opt.add_option('-x', '--exc',     dest='exc',       default=['.svn'], action='append',      help='Extension of Files')
opt.add_option('-q', '--quiet',   dest='isQuiet',   default=True,  action='store_false', help='Print files')
opt.add_option('-p', '--pattern', dest='isPrtPat',  default=True,  action='store_false', help='Print pattern')
opt.add_option('-r', '--replace', dest='isReplace', default=False, action='store_true',  help='Replace word')
opt.add_option('-m', '--move',    dest='isMove',    default=False, action='store_true',  help='Move file')

(options, args) = opt.parse_args()


stdscr = curses.initscr()
curses.noecho()
curses.cbreak()

while True:
  #proc = os.popen('cal;date')
  #proc = os.popen('qstatu')
  proc = os.popen('Qstat -ju | grep KIMtest')
  strings = proc.readlines()
  nlines = len(strings)
  for i in range(nlines):
    stdscr.addstr(i, 0, strings[i][:-1])
  stdscr.refresh()
  time.sleep(2)
curses.echo()
curses.nocbreak()
curses.endwin()


'''
while True:
   #proc = os.popen('qstatu')
   proc = os.popen('cal;date')
   strings = proc.readlines()
   nlines = len(strings)
   for i in range(nlines):
     print strings[i][:-1]
   time.sleep(2.0)
'''
