#!/usr/bin/env python

import sys
from optparse import OptionParser

# load My Class
sys.path.append('/home/jhkim/Study/Library/Python/draw_latlon_fig')
from drawer_latlon import *


#s_file = '/scratch/jhkim/TestBed/KIM/Output/2.2/ne30/gnu/10h/SW_G/101/UP-20110725220000-000011.nc'
#d_file = '/scratch/jhkim/TestBed/KIM/Output/2.5/ne30/gnu/10h/SW_G/101/UP-20110725220000-000010.nc'
s_file = '/scratch/jhkim/TestBed/KIM/Output/2.5.04_org/ne30/gnu/10h/SW_G/101/UP-20110725220000-000010.nc'
d_file = '/scratch/jhkim/TestBed/Data/single/UP-20110725220000-000010.nc'

# 2 plots
remap = drawer_latlon_2grid(s_file,d_file)
#remap.set_variables(['ps','crain'])
remap.set_variables(['ps'])
remap.set_coordinates('lats', 'lons', 'lats', 'lons')
remap.draw('',0,'test.png',ongrid=True)

